Xprime = function(Xprime(X))

Xprime = [X(4) X(5) X(6) T1/m*sin(-theta)+T3/m*sin(-theta) T2/m*sin(phi)+T4/m*sin(phi)...
    T1/m*cos(-theta)+T3/m*cos(-theta)+T2/m*sin(phi)+T4/m*sin(phi)-m*g X(9) X(10)...
    1/Ix*(T4-T2)*L2 1/Iy*(T3-T1)*L1];